In [3]:
import pandas as pd

In [72]:
tabela = pd.read_excel('caixa-mensal-2023.xlsx', sheet_name=0)
tabela = tabela.dropna(axis=1, how='all')
tabela = tabela.dropna(axis=0, how='all')
tabela = tabela.drop(["DATA", "PC", "SEMANA", "NOMES"], axis=1)
# display(tabela["TOTAL D"])
display(tabela)

,CAIXA,PIX,CARTAO,IFOOD,T DIA,T MÊS,Unnamed: 10,MPPC,DESPESAS,TOTAL D,...,SEMANAS,DIZ,SALGADO,EMBALAGENS,AÇAI/MILK,FEIRA/PAD.,COMBUSTIVEL,MERCADO,PARTICULAR,OUTROS
0,0.0,0.00,0.00,0.000,0.000,0.000,0.00000,280.0,0.00,0.00,...,segunda,0,0.0,0.00,0,0.0,0,0.00,0,0.00
1,185.0,59.56,458.40,0.000,702.960,702.960,28.11840,320.0,333.21,333.21,...,terça,30,0.0,0.00,115,0.0,0,38.21,150,0.00
2,165.0,15.00,59.70,54.850,294.550,997.510,11.78200,320.0,709.85,1043.06,...,quarta,12,0.0,537.85,110,0.0,50,0.00,0,0.00
3,145.5,0.00,34.51,202.680,382.690,1380.200,15.30760,400.0,300.59,1343.65,...,quinta,16,0.0,0.00,0,25.5,0,234.09,0,25.00
4,121.0,166.30,321.47,88.960,697.730,2077.930,27.90920,600.0,27.00,1370.65,...,sexta,27,0.0,0.00,0,0.0,0,0.00,0,0.00
5,0.0,0.00,0.00,31.980,31.980,2109.910,1.27920,0.0,621.00,1991.65,...,sabado,0,606.0,0.00,0,0.0,15,0.00,0,0.00
6,172.0,16.10,266.60,120.350,575.050,2684.960,23.00200,0.0,507.84,2499.49,...,segunda,23,0.0,0.00,0,0.0,0,484.84,0,0.00
7,142.0,45.40,166.31,89.397,443.107,3128.067,17.72428,480.0,3139.29,5638.78,...,terça,18,0.0,62.70,0,12.0,0,0.00,122,2924.59
8,172.0,97.30,231.41,153.940,654.650,3782.717,26.18600,400.0,162.00,5800.78,...,quarta,25,0.0,0.00,115,10.0,12,0.00,0,0.00
9,152.0,60.40,211.00,152.430,575.830,4358.547,23.03320,0.0,1286.70,7087.48,...,quinta,24,1167.5,60.20,0,35.0,0,0.00,0,0.00
10,100.0,48.20,245.59,19.000,412.790,4771.337,16.51160,480.0,17.00,7104.48,...,sexta,17,0.0,0.00,0,0.0,0,0.00,0,0.00
11,72.0,0.00,37.00,0.000,109.000,4880.337,4.36000,160.0,50.00,7154.48,...,sabado,0,0.0,0.00,0,0.0,50,0.00,0,0.00
12,101.0,20.00,97.00,18.990,236.990,5117.327,9.47960,0.0,0.00,7154.48,...,segunda,0,0.0,0.00,0,0.0,0,0.00,0,0.00
13,72.0,8.00,125.00,42.330,247.330,5364.657,9.89320,0.0,200.00,7354.48,...,terça,0,0.0,0.00,0,0.0,0,0.00,0,200.00
14,150.0,7.20,169.96,0.000,327.160,5691.817,13.08640,0.0,0.00,7354.48,...,quarta,0,0.0,0.00,0,0.0,0,0.00,0,0.00
15,117.0,12.00,91.10,0.000,220.100,5911.917,8.80400,0.0,115.00,7469.48,...,quinta,0,0.0,0.00,115,0.0,0,0.00,0,0.00
16,145.0,20.80,101.80,49.980,317.580,6229.497,12.70320,0.0,50.00,7519.48,...,sexta,0,0.0,0.00,0,0.0,50,0.00,0,0.00
17,80.0,0.00,89.00,0.000,169.000,6398.497,6.76000,0.0,94.46,7613.94,...,sabado,0,0.0,0.00,0,0.0,0,81.46,13,0.00
18,74.0,0.00,115.90,98.980,288.880,6687.377,11.55520,0.0,0.00,7613.94,...,segunda,0,0.0,0.00,0,0.0,0,0.00,0,0.00
19,73.0,0.00,41.51,0.000,114.510,6801.887,4.58040,0.0,0.00,7613.94,...,terça,0,0.0,0.00,0,0.0,0,0.00,0,0.00
20,18.0,0.00,234.50,95.200,347.700,7149.587,13.90800,0.0,45.00,7658.94,...,quarta,0,0.0,0.00,0,0.0,0,45.00,0,0.00
21,86.0,83.30,212.60,35.200,417.100,7566.687,16.68400,0.0,58.50,7717.44,...,quinta,0,0.0,0.00,0,43.5,0,15.00,0,0.00
22,63.0,36.90,89.80,157.550,347.250,7913.937,13.89000,0.0,300.00,8017.44,...,sexta,0,300.0,0.00,0,0.0,0,0.00,0,0.00
23,78.0,34.40,103.89,105.980,322.270,8236.207,12.89080,0.0,50.00,8067.44,...,sabado,0,0.0,0.00,0,0.0,50,0.00,0,0.00
24,80.0,0.00,78.20,61.880,220.080,8456.287,8.80320,0.0,0.00,8067.44,...,segunda,0,0.0,0.00,0,0.0,0,0.00,0,0.00
25,145.0,45.00,57.80,64.680,312.480,8768.767,12.49920,0.0,46.49,8113.93,...,terça,0,0.0,0.00,0,0.0,0,46.49,0,0.00
26,2708.5,775.86,3640.05,1644.357,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,192,2073.5,660.75,455,126.0,227,945.09,285,3149.59

In [5]:
soma_pix = tabela["PIX"].sum()
soma_cartao = tabela["CARTAO"].sum()
soma_ifood = tabela["IFOOD"].sum()
soma_caixa = tabela["CAIXA"].sum()
soma = soma_caixa + soma_cartao + soma_ifood + soma_pix
print(soma_pix, soma_caixa, soma_cartao, soma_ifood)
print(soma)

1551.72 5417.0 7280.1 3288.714
17537.534

In [92]:
print(tabela.at[1, "CAIXA"])
print(tabela.at[1, "PIX"])
print(tabela.at[1, "CARTAO"])
print(tabela.at[1, "IFOOD"])

tabelas_entrada = ["CAIXA", "PIX", "CARTAO", "IFOOD"]
tabelas_saida = ["DIZ", "SALGADO", "EMBALAGENS", "AÇAI/MILK", "FEIRA/PAD.", "COMBUSTIVEL", "MERCADO", "PARTICULAR", "OUTROS"]

185.0
59.56
458.4
0.0

In [93]:
def entrada_ou_saida_mes(colunas):
    total = 0
    contador = 0
    total_entrada_mes = []

    for col in colunas:
        for contador in range(26):
            total += tabela.at[contador, col]
            contador += 1

        total_entrada_mes.append(round(total, 2))
        total = 0

    return total_entrada_mes

# print(entrada_ou_saida_mes(tabelas_entrada))
print(entrada_ou_saida_mes(tabelas_saida))

[192, 2073.5, 660.75, 455, 126.0, 227, 945.09, 285, 3149.59]

In [83]:
# Total de entrada mensal

c = 0
total = 0
total_entrada_mes = []

for tab in tabelas_entrada:
    for c in range(26):
        total += tabela.at[c, tab]
        c+=1
    total_entrada_mes.append(round(total, 2))
    total = 0

print(total_entrada_mes)

[2708.5, 775.86, 3640.05, 1644.36]

In [94]:
def total_dia(colunas):
    linhas = 1
    dias = 1
    total = 1
    contador = 1
    total_mensal = 0.00
    total_diario = []

    for contador in range(26):
        for col in colunas:
            if linhas > 25:
                break
            
            total += tabela.at[linhas, col]

            if col == colunas[-1]:
                dia = {
                    dias: round(total, 2)
                }

                total_diario.append(dia)
                total_mensal += total
                
                total = 0
                linhas += 1
                dias += 1

    return {
        "total_diario": total_diario,
        "total_mensal": total_mensal
    }

# print(total_dia(tabelas_entrada))
print(total_dia(tabelas_saida))

{'total_diario': [{1: 334.21}, {2: 709.85}, {3: 300.59}, {4: 27.0}, {5: 621.0}, {6: 507.84}, {7: 3139.29}, {8: 162.0}, {9: 1286.7}, {10: 17.0}, {11: 50.0}, {12: 0.0}, {13: 200.0}, {14: 0.0}, {15: 115.0}, {16: 50.0}, {17: 94.46}, {18: 0.0}, {19: 0.0}, {20: 45.0}, {21: 58.5}, {22: 300.0}, {23: 50.0}, {24: 0.0}, {25: 46.49}], 'total_mensal': 8114.93}

In [85]:
# Total de caixa diario e mensal

x, z, t = 1, 1, 0
dias = 1
total_mensal = 0.00
total_diario = []

for x in range(26):
    for tab in tabelas_entrada:
        if z > 25:
            break
        
        t += tabela.at[z, tab]

        if tab == "IFOOD":
            dia = {
                dias: round(t, 2)
            }
            total_diario.append(dia)
            
            total_mensal += t
            
            t = 0
            z += 1
            dias += 1
            
print(total_diario)
print(total_mensal)

[{1: 702.96}, {2: 294.55}, {3: 382.69}, {4: 697.73}, {5: 31.98}, {6: 575.05}, {7: 443.11}, {8: 654.65}, {9: 575.83}, {10: 412.79}, {11: 109.0}, {12: 236.99}, {13: 247.33}, {14: 327.16}, {15: 220.1}, {16: 317.58}, {17: 169.0}, {18: 288.88}, {19: 114.51}, {20: 347.7}, {21: 417.1}, {22: 347.25}, {23: 322.27}, {24: 220.08}, {25: 312.48}]
8768.767